apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: login-front
spec:
  replicas: 1
  selector:
    matchLabels:
      app: login-front
  template:
    metadata:
      labels:
        app: login-front
    spec:
      containers:
      - name: login-front
        image: jairvercosa/login-node
        ports:
        - containerPort: 4000
        env:
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP

---

apiVersion: v1
kind: Service
metadata:
  name: login-front
  labels:
    app: login-front
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 4000
    protocol: TCP
    name: http
  selector:
    app: login-front

---